import Header from "@/components/Header";
import { NextThemeProvider } from "@/providers/next-theme";
import ReactQueryProvider from "@/providers/react-query";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { ReduxStoreProvider } from "@/providers/redux";
import Footer from "@/components/Footer";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Luna Factories",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <Toaster position="bottom-right" />
          <NextThemeProvider
            attribute={"class"}
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <ReduxStoreProvider>
              <ReactQueryProvider>
                <Header />
                {children}
                <Footer />
              </ReactQueryProvider>
            </ReduxStoreProvider>
          </NextThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
